spring:
  datasource:
    url: jdbc:mysql://${DB_SERVER}:${DB_PORT:3306}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    properties:
      hibernate:
        generate_statistics: 'true'
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    show-sql: 'true'
logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
server:
  port: 8081
management:
  endpoint:
    shutdown:
      enabled: true 